apiVersion: apps/v1
kind: Deployment
metadata:
  name: election-deploy
  labels:
    app: etcd-election
spec:
  replicas: 3
  selector:
    matchLabels:
      app: etcd-election
  template:
    metadata:
      labels:
        app: etcd-election
    spec:
      containers:
        - name: etcd-election
          image: pambrose/etcd-election:1.0.23
          ports:
            - containerPort: 8081
          env:
            - name: SIMPLE_SERVICE_VERSION
              value: "0.1"

---

apiVersion: v1
kind: Service
metadata:
  name: election-service
spec:
  selector:
    app: etcd-election
  ports:
    - port: 8080
      targetPort: 8081
  type: LoadBalancer
