apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-deploy
  labels:
    app: etcd-counter
spec:
  replicas: 3
  selector:
    matchLabels:
      app: etcd-counter
  template:
    metadata:
      labels:
        app: etcd-counter
    spec:
      containers:
        - name: etcd-counter
          image: pambrose/etcd-counter:1.0.20
          ports:
            - containerPort: 8082
          env:
            - name: SIMPLE_SERVICE_VERSION
              value: "0.1"

---

apiVersion: v1
kind: Service
metadata:
  name: counter-service
spec:
  selector:
    app: etcd-counter
  ports:
    - port: 8080
      targetPort: 8082
  type: LoadBalancer
