apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-deploy
  labels:
    app: prometheus-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-agent
  template:
    metadata:
      labels:
        app: prometheus-agent
    spec:
      containers:
        - name: prometheus-agent
          image: pambrose/prometheus-agent:1.4.1
          ports:
            - containerPort: 8083
              name: Metrics-port
            - containerPort: 8093
              name: Admin-port
          env:
            - name: SIMPLE_SERVICE_VERSION
              value: "0.1"

---

apiVersion: v1
kind: Service
metadata:
  name: agent-service
spec:
  selector:
    app: prometheus-agent
  ports:
    - port: 8083
      targetPort: 8083
      name: Metrics-port
    - port: 8093
      targetPort: 8093
      name: Admin-port
  type: LoadBalancer
